import setuptools

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setuptools.setup(
    name="jira-task-classification",
    version="0.0.1",
    author="Shivathanu Gopirajan Chitra",
    author_email="gcshivathanu@gmail.com",
    description="Build classification models that enable to classify task to related categories",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/promessa-project/jira-task-classification",
    classifiers=[
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
    ],
    license='unlicense',
    packages=setuptools.find_packages(),
    install_requires=[
        "beautifulsoup4==4.9.3",
        "blis==0.7.4",
        "bs4==0.0.1",
        "catalogue==2.0.4",
        "certifi==2020.6.20",
        "chardet==3.0.4",
        "click==7.1.2",
        "cymem==2.0.5",
        "en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0-py3-none-any.whl",
        "Flask==2.0.1",
        "Flask-Cors==3.0.10",
        "idna==2.10",
        "ipython-genutils==0.2.0",
        "itsdangerous==2.0.1",
        "Jinja2==3.0.1",
        "joblib==1.0.1",
        "MarkupSafe==2.0.1",
        "murmurhash==1.0.5",
        "numpy==1.20.1",
        "packaging==20.9",
        "pandas==1.2.4",
        "parso==0.8.2",
        "Paste==3.5.0",
        "pathy==0.5.2",
        "preshed==3.0.5",
        "pydantic==1.7.4",
        "Pygments==2.7.1",
        "PyMySQL==1.0.2",
        "pyparsing==2.4.7",
        "pyrsistent==0.17.3",
        "python-dateutil==2.8.1",
        "pytz==2021.1",
        "requests==2.24.0",
        "scikit-learn==0.24.2",
        "scipy==1.6.3",
        "six==1.15.0",
        "sklearn==0.0",
        "smart-open==3.0.0",
        "soupsieve==2.2",
        "spacy==3.0.6",
        "spacy-legacy==3.0.6",
        "srsly==2.4.1",
        "text-unidecode==1.3",
        "thinc==8.0.5",
        "threadpoolctl==2.1.0",
        "tqdm==4.59.0",
        "traitlets==5.0.4",
        "typer==0.3.2",
        "Unidecode==1.2.0",
        "urllib3==1.25.10",
        "waitress==2.0.0",
        "wasabi==0.8.2",
        "wcwidth==0.2.5",
        "Werkzeug==2.0.1",
        "word2number==1.1",
        "xgboost==1.4.2",
    ],
    python_requires=">=3.9",
)